name: On Push to Main Branch

on:
  push:
    branches: [ master ]

env:
  ECR_REPO: public.ecr.aws/z0d6s8x8

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: docker/setup-buildx-action@v1
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::783680406432:role/GithubActionsPublishRole-test-us-east-1
        aws-region: us-east-1
    - name: Login to Public ECR
      uses: docker/login-action@v1
      with:
        registry: ${{ env.ECR_REPO }}
    - name: Setup Push to ECR
      run: |
        export VERSION=$(git describe --tags)
        export TAG_BASE=$(echo $GITHUB_REPOSITORY | sed s#/#-#)-test
        echo VERSION=$VERSION >> $GITHUB_ENV
        echo TAG_BASE=$TAG_BASE >> $GITHUB_ENV
    - name: Build and push container images
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          ${{ env.TAG_BASE }}:latest
          ${{ env.TAG_BASE }}:${{ env.VERSION }}
        push: false
