name: On Push to Main Branch

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: docker/setup-buildx-action@v1
    - name: Build the Docker image
      run: |
        export VERSION=$(git describe --tags)
        echo VERSION=$VERSION >> $GITHUB_ENV
        docker build . --file Dockerfile --tag my-image-name:$VERSION
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push container images
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          #ghcr.io/jniebuhr/aws-pca-issuer:latest
          #ghcr.io/jniebuhr/aws-pca-issuer:${{steps.tag.outputs.tag}}
        push: false

