name: On Push to Main Branch

on:
  push:
    branches: [ master ]

env:
  ECR_REPO: public.ecr.aws/z0d6s8x8

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: docker/setup-buildx-action@v1
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::783680406432:role/GithubActionsPublishRole-test-us-east-1
        aws-region: us-east-1
    - name: Login to ECR
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO
    - name: Setup Push to ECR
      run: |
        export VERSION=$(git describe --tags)
        export TEST_BASE=$(cat $GITHUB_REPOSITORY | sed s/\//-/)-test
        echo VERSION=$VERSION >> $GITHUB_ENV
        echo TEST_BASE=$TEST_BASE >> $GITHUB_ENV
    - name: Build and push container images
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          divyansh-gupta-aws-privateca-issuer-test:latest
          divyansh-gupta-aws-privateca-issuer-test:$VERSION
          
          #ghcr.io/jniebuhr/aws-pca-issuer:latest
          #ghcr.io/jniebuhr/aws-pca-issuer:${{steps.tag.outputs.tag}}
        push: false
