name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  ECR_REPO: public.ecr.aws/k1n1h4h4
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release version
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Setup Dockerx
        uses: docker/setup-buildx-action@v1
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::105154636954:role/GithubActionsPublishRole-prod-us-east-1
          aws-region: us-east-1
      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
        env:
          AWS_REGION: us-east-1
      - name: Setup Push to ECR
        run: |
          export TAG_BASE=${{ env.ECR_REPO }}/$(echo $GITHUB_REPOSITORY | sed s#/#-#)
          echo TAG_BASE=$TAG_BASE >> $GITHUB_ENV
      - name: Build and push container images
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ${{ env.TAG_BASE }}:latest
            ${{ env.TAG_BASE }}:${{steps.tag.outputs.tag}}
          push: true
#       - name: Publish Helm chart
#         uses: stefanprodan/helm-gh-pages@master
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           linting: "off"
#           app_version: ${{ steps.tag.outputs.tag }}
